<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/._*</DefaultItemExcludes>
    <RootNamespace>SmartTelescopeSort.Core</RootNamespace>
    <AssemblyName>SmartTelescopeSort.Core</AssemblyName>
    <Version>1.2.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.json" LogicalName="SmartTelescopeSort.Core.Resources.%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SmartTelescopeSort.Core.Tests" />
  </ItemGroup>
</Project>
